_name_: csv_dataset
data_dir: ???  # User must specify path to directory containing train.csv, dev.csv, test.csv
max_length: 1024
max_length_val: ${.max_length}
max_length_test: ${.max_length}
d_output: 2
use_padding: True
padding_side: 'left'
add_eos: False
batch_size: 32
__l_max: ${.max_length}
shuffle: true
